#!/bin/bash
# Populate the TESTING database with demo records, using the application's own
# demo-mode generator rather than hand-written fixtures.
#
# Why: docker/init.sql ships schema, modules, settings and lookup tables, but no
# transactional data — no employees, attendance, overtime, timesheets. Many specs
# assert on "the seeded X", so they fail on an otherwise healthy app. Generating
# through extensions/demo-mode keeps the fixtures consistent with what the product
# itself considers valid data (correct FKs, statuses and approval chains) instead of
# a parallel set of INSERTs that drifts.
#
# Only the generators available in the free build are called. demo-mode ships the
# pro ones too (expenses, candidates, task lists, performance reviews, payroll,
# leave), but DemoDataService gates each behind `$isPro && class_exists(...)`, so
# they are no-ops here — calling them would just print failures. Overtime is
# deliberately NOT pro-gated: it is a core module.
#
# Idempotent in the sense that matters: it checks whether data already exists and
# does nothing if so, because the generator appends rather than upserts.
#
# Usage:  e2e/bootstrap/seed-demo-data.sh          (called by globalSetup)
#         E2E_FORCE_DEMO=1 e2e/bootstrap/seed-demo-data.sh   (generate again anyway)
set -uo pipefail

BASE="${E2E_APP_BASE:-http://localhost:9380/app}"
DB_CONTAINER="${DB_CONTAINER:-icehrm-testing-mysql-testing-1}"
DB_USER="${DB_USER:-testing}"
DB_PASS="${DB_PASS:-testing}"
DB_NAME="${DB_NAME:-icehrm}"
PASSWORD="${E2E_PASSWORD:-Admin123\$}"
JAR="$(mktemp -t icehrm-e2e-seed)"
trap 'rm -f "$JAR"' EXIT

row_count() {
  docker exec "$DB_CONTAINER" mysql -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -N \
    -e "SELECT COUNT(*) FROM \`$1\`;" 2>/dev/null || echo 0
}

# Attendance is generated by every path below, so it is a good "has anything run?"
# probe. Employees alone is not: seed-users.sh creates six of those.
EXISTING="$(row_count Attendance)"
if [ "${EXISTING:-0}" -gt 0 ] && [ "${E2E_FORCE_DEMO:-0}" != "1" ]; then
  echo "seed-demo-data: demo data already present (Attendance=${EXISTING}) — skipping."
  echo "                re-generate with E2E_FORCE_DEMO=1"
  exit 0
fi

# --- authenticate ------------------------------------------------------------
CSRF="$(curl -s -c "$JAR" "$BASE/login.php" | grep -oE 'value="[a-f0-9]{64}"' | head -1 | grep -oE '[a-f0-9]{64}')"
curl -s -b "$JAR" -c "$JAR" -o /dev/null -X POST "$BASE/login.php" \
  --data-urlencode "username=admin" \
  --data-urlencode "password=${PASSWORD}" \
  --data-urlencode "csrf=${CSRF}"

# The SPA shell embeds a short-lived JWT; the REST API wants it as a Bearer token.
TOKEN="$(curl -s -b "$JAR" "$BASE/ui/" | grep -oE 'eyJ[A-Za-z0-9_.-]{40,}' | head -1)"
if [ -z "$TOKEN" ]; then
  echo "seed-demo-data: could not obtain an API token — is admin able to log in?" >&2
  echo "                run e2e/bootstrap/seed-users.sh first." >&2
  exit 1
fi

gen() { # gen <endpoint> <json-body> <label>
  local out
  out="$(curl -s -m 300 -X POST "$BASE/api/demo-mode/$1" \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Content-Type: application/json' \
    -d "$2" 2>/dev/null)"
  if printf '%s' "$out" | grep -q '"error"'; then
    printf '  %-22s failed: %s\n' "$3" "$(printf '%s' "$out" | head -c 120)"
  else
    printf '  %-22s ok\n' "$3"
  fi
}

echo "seed-demo-data: generating demo records via the app's demo-mode extension…"

# Core set: employees + users + details + clients/projects + attendance +
# timesheets. Everything else builds on the employees this creates.
gen generate-all        '{}'                               "core (generate-all)"

# Area-specific generators, each backing a group of specs that assert on seeded rows.
gen overtime            '{"count":15}'                     "overtime"
gen attendance-today    '{"percentage":80}'                "today's attendance"

# --- give the login accounts a slice of the generated data --------------------
#
# The generator invents its own employees and hangs everything off those, so the
# accounts the specs log in as (user1, user3, manager) end up owning nothing and
# every "my attendance / my overtime" tab renders empty. Reassign a slice of the
# demo rows to them, keeping the reporting line intact so the manager-scope specs
# still see subordinate data.
echo "seed-demo-data: linking demo records to the e2e accounts…"
docker exec -i "$DB_CONTAINER" mysql -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" 2>/dev/null <<'SQL'
SET @u1  = (SELECT employee FROM Users WHERE username = 'user1');
SET @u3  = (SELECT employee FROM Users WHERE username = 'user3');
SET @mgr = (SELECT employee FROM Users WHERE username = 'manager');

-- Move a handful of rows per table onto each account. LIMIT keeps the rest with the
-- demo employees, so admin-facing "many employees" assertions still hold.
--
-- EmployeeOvertime matters beyond the "my overtime" tabs: security-sm-mapping.spec.js
-- asserts user1 receives their OWN rows back, so it fails if user1 owns none.
UPDATE Attendance        SET employee = @u1  WHERE employee <> @u1  ORDER BY id        LIMIT 40;
UPDATE Attendance        SET employee = @u3  WHERE employee NOT IN (@u1, @u3) ORDER BY id DESC LIMIT 25;
UPDATE EmployeeOvertime  SET employee = @u1  WHERE employee <> @u1  ORDER BY id        LIMIT 10;
UPDATE EmployeeOvertime  SET employee = @mgr WHERE employee NOT IN (@u1, @mgr) ORDER BY id DESC LIMIT 5;

-- Demo employees report to the e2e manager, so manager-scope lists are non-empty.
UPDATE Employees SET supervisor = @mgr
 WHERE supervisor IS NULL AND id NOT IN (@u1, @u3, @mgr) AND id > 1
 ORDER BY id LIMIT 6;
SQL

echo "seed-demo-data: row counts now —"
# EmployeeTimeSheets is plural — the singular name counted nothing and always
# reported 0. TaskList and the leave tables are dropped: pro-only data.
for t in Employees Attendance EmployeeOvertime EmployeeTimeSheets; do
  printf '  %-22s %s\n' "$t" "$(row_count "$t")"
done
docker exec "$DB_CONTAINER" mysql -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -N -e "
SELECT CONCAT('  ', u.username, ': attendance=', (SELECT COUNT(*) FROM Attendance WHERE employee=u.employee),
              ' overtime=', (SELECT COUNT(*) FROM EmployeeOvertime WHERE employee=u.employee),
              ' reports=', (SELECT COUNT(*) FROM Employees WHERE supervisor=u.employee))
  FROM Users u WHERE u.username IN ('user1','user3','manager') ORDER BY u.username;" 2>/dev/null
