FROM alpine:3.20
LABEL Maintainer="Thilina, Pituwala <thilina@icehrm.com>" \
      Description="IceHrm Docker Container with Nginx & PHP-FPM based on Alpine Linux."

ARG EXE_ENV


# Install packages
RUN apk --no-cache add php83 php83-fpm php83-opcache php83-mysqli php83-json php83-openssl php83-curl \
    php83-zlib php83-xml php83-phar php83-intl php83-dom php83-simplexml php83-xmlreader php83-ctype php83-session \
    php83-mbstring php83-gd nginx supervisor curl

# Create symlink for php command
RUN ln -sf /usr/bin/php83 /usr/bin/php

# Configure supervisord
COPY docker/worker/config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# persistent / runtime deps

RUN apk add --no-cache \
        ttf-dejavu ttf-droid ttf-freefont ttf-liberation \
    ;

# Setup document root
RUN mkdir -p /var/www/html

# Add application
WORKDIR /var/www/html
COPY ./app /var/www/html/app/
COPY ./core /var/www/html/core/
COPY ./extensions /var/www/html/extensions/
COPY ./web /var/www/html/web/
COPY ./index.php /var/www/html/index.php
COPY ./docker/$EXE_ENV/config/config.php /var/www/html/app/config.php


COPY ./docker/worker/config/ice-cron /etc/crontabs/root

CMD /usr/sbin/crond -f -l 8
