<?php
namespace Classes;

use Classes\Crypt\IceCrypt;
use Model\Setting;
use Utils\LogManager;

class SettingsManager
{

    /**
     * Legacy marker: value encrypted under (instanceId . instanceKey).
     * Still read so existing settings keep decrypting; never written any more.
     */
    const ENCRYPTED_PREFIX = 'iceenc_';

    /**
     * Current marker: value encrypted under APP_SEC.
     *
     * The legacy key was weak and frequently absent — 'Instance: Key' is only written
     * when an admin pastes a verification key into the Connect dialog, so on most
     * installs the key material collapsed to the instance id alone, which is md5(time())
     * and stored in the very same database as the ciphertext.
     */
    const ENCRYPTED_PREFIX_V2 = 'iceenc2_';

    private static $me = null;

    private $encryptedSettings = [];

    private function __construct()
    {
        $this->addEncryptedSetting('SAML: X.509 Certificate');
        $this->addEncryptedSetting('LDAP: Manager Password');
        $this->addEncryptedSetting('Microsoft: Client Secret');
        $this->addEncryptedSetting('Google: Client Secret');
    }

    public static function getInstance()
    {
        if (empty(self::$me)) {
            self::$me = new SettingsManager();
        }

        return self::$me;
    }

    public function addEncryptedSetting($name)
    {
        if (!$this->isEncryptedSetting($name)) {
            $this->encryptedSettings[] = $name;
        }
    }

    public function isEncryptedSetting($name)
    {
        return in_array($name, $this->encryptedSettings);
    }

    /**
     * Raw read of the stored instance key — returns null when there is none.
     *
     * Do NOT change this to generate a key like BaseService::getInstanceKey() does.
     * Its only caller is legacyEncryptionKey(), which needs the value exactly as it was
     * when the legacy ciphertexts were written.
     */
    public function getInstanceKey()
    {
        $settings = new Setting();
        $settings->Load("name = ?", array("Instance: Key"));
        if ($settings->name != "Instance: Key") {
            return null;
        }
        return $settings->value;
    }

	public function getHiddenSettings() {
		// Advanced Timesheets is retired (ignored by the new UI); it is hidden from
		// the settings screen and forced off — see getSetting().
		$hidden = ['System: Advanced Timesheets'];
		if (class_exists("\\Classes\\ProVersion")) {
			$pro = new \Classes\ProVersion();
			if (method_exists($pro, 'hiddenSettings')) {
				$hidden = array_merge($hidden, $pro->hiddenSettings());
			}
		}

		return $hidden;
	}

    /**
     * Key material for settings encrypted before the APP_SEC switch. Kept only so those
     * values still decrypt; never used to encrypt anything new.
     *
     * Deliberately reads the stored key directly rather than through
     * BaseService::getInstanceKey(), which generates one when the install has none —
     * generating here would both change this key half and provision a key as a
     * side effect of a decrypt.
     *
     * When BaseService did generate the key, the install had none at the time these
     * ciphertexts were written, so the key half was ''. The marker it leaves behind is
     * what lets us reproduce that; without this branch, provisioning would silently
     * break every pre-existing 'iceenc_' value (SMTP, LDAP, SAML and OAuth secrets).
     */
    private function legacyEncryptionKey()
    {
        $id = BaseService::getInstance()->getInstanceId();

        $marker = new Setting();
        $marker->Load("name = ?", array(BaseService::INSTANCE_KEY_AUTOGENERATED));
        if ($marker->name === BaseService::INSTANCE_KEY_AUTOGENERATED) {
            return $id;
        }

        return $id.$this->getInstanceKey();
    }

    private function encrypt($value)
    {
        return IceCrypt::encrypt($value, BaseService::getInstance()->getAppSecret());
    }

    /**
     * True when the stored value already carries either encryption marker, so a
     * re-save cannot encrypt an already-encrypted value a second time.
     */
    private function hasEncryptionPrefix($value)
    {
        $value = (string)$value;

        return substr($value, 0, strlen(self::ENCRYPTED_PREFIX_V2)) === self::ENCRYPTED_PREFIX_V2
            || substr($value, 0, strlen(self::ENCRYPTED_PREFIX)) === self::ENCRYPTED_PREFIX;
    }

    public function encryptSetting($name, $value)
    {
        // check the existence of prefix and encrypt only if need to avoid double encryption
        if ($this->isEncryptedSetting($name) && !$this->hasEncryptionPrefix($value)) {
            $value = self::ENCRYPTED_PREFIX_V2.$this->encrypt($value);
        }

        return $value;
    }

    private function decrypt($value, $key)
    {
        // Falls back to AesCtr for values stored before the switch.
        return IceCrypt::decrypt($value, $key);
    }

    public function decryptSetting($name, $value)
    {
        if (!$this->isEncryptedSetting($name)) {
            return $value;
        }

        $value = (string)$value;

        // Dispatch on the marker: values written since the APP_SEC switch use the
        // strong key, anything older keeps using the legacy derivation. Saving a
        // setting again transparently re-encrypts it under the new key.
        if (substr($value, 0, strlen(self::ENCRYPTED_PREFIX_V2)) === self::ENCRYPTED_PREFIX_V2) {
            return $this->decrypt(
                substr($value, strlen(self::ENCRYPTED_PREFIX_V2)),
                BaseService::getInstance()->getAppSecret()
            );
        }

        if (substr($value, 0, strlen(self::ENCRYPTED_PREFIX)) === self::ENCRYPTED_PREFIX) {
            return $this->decrypt(
                substr($value, strlen(self::ENCRYPTED_PREFIX)),
                $this->legacyEncryptionKey()
            );
        }

        return $value;
    }

    public function getSetting($name)
    {
        // Advanced Timesheets is retired — always report it as off ("No"/0) so no
        // consumer (legacy or new UI) can re-enable it. Hidden from the settings
        // screen too (see getHiddenSettings()).
        if ($name === 'System: Advanced Timesheets') {
            return '0';
        }

        if (class_exists("\\Classes\\ProVersion")) {
            $pro = new ProVersion();
            $val =  $pro->getSetting($name);
            if (!empty($val)) {
                return $val;
            }
        }

        $setting = new Setting();
        $setting->Load("name = ?", array($name));
        $value = null;
        if ($setting->name == $name) {
            $value = $setting->value;
        }

        if (null === $value) {
            return null;
        }

        return $this->decryptSetting($name, $value);
    }

    public function setSetting($name, $value)
    {
        $setting = new Setting();
        $setting->Load("name = ?", array($name));
        if ($setting->name !== $name) {
            return;
        }

        $setting->value = $this->encryptSetting($name, $value);
        $setting->Save();
    }

    public function addSetting($name, $value)
    {
        $setting = new Setting();
        $setting->Load("name = ?", array($name));
        if ($setting->name == $name) {
            $setting->value = $this->encryptSetting($name, $value);
            $setting->Save();
        } else {
            $setting->name = $name;
            $setting->value = $this->encryptSetting($name, $value);
            $setting->description = '';
            $setting->meta = '';
            $setting->Save();
        }
    }

    public function getDeprecatedSettings()
    {
        return [
            'Attendance: Work Week Start Day',
            'Attendance: Overtime Calculation Class'
        ];
    }

	public function getS3Settings($private = true) {
		$obj = new \stdClass();
		if ($private) {
			$obj->uploadFilesToS3 = SettingsManager::getInstance()->getSetting("Files: Upload Files to S3");
			$obj->uploadFilesToS3Key = SettingsManager::getInstance()->getSetting(
				"Files: Amazon S3 Key for File Upload"
			);
			$obj->uploadFilesToS3Secret = SettingsManager::getInstance()->getSetting(
				"Files: Amazon S3 Secret for File Upload"
			);
			$obj->s3Bucket = SettingsManager::getInstance()->getSetting("Files: S3 Bucket");
			$obj->webUrl = SettingsManager::getInstance()->getSetting("Files: S3 Web Url");
			$obj->awsRegion = SettingsManager::getInstance()->getSetting("System: AWS Region");
		} else {
			$obj->uploadFilesToS3 = SettingsManager::getInstance()->getSetting("Files: Upload Files to S3 for Editor");
			$obj->uploadFilesToS3Key = SettingsManager::getInstance()->getSetting(
				"Files: Amazon S3 Key for Editor File Upload"
			);
			$obj->uploadFilesToS3Secret = SettingsManager::getInstance()->getSetting(
				"Files: Amazon S3 Secret for Editor File Upload"
			);
			$obj->s3Bucket = SettingsManager::getInstance()->getSetting("Files: S3 Bucket for Editor");
			$obj->webUrl = SettingsManager::getInstance()->getSetting("Files: S3 Web Url for Editor");
			$obj->awsRegion = SettingsManager::getInstance()->getSetting("System: AWS Region for Editor");
		}

		return $obj;
	}
}
