<?php
/**
 * Mint an updater link from the command line.
 *
 *     php updater/token.php
 *
 * The updater normally requires a link generated by the update banner inside IceHRM.
 * That is a deliberate gate — but it would also lock you out at the worst moment, when
 * the application is too broken to sign into and the updater is the tool you need. This
 * is the way back in.
 *
 * It is NOT a bypass. It runs only under the CLI SAPI (refusing outright over the web)
 * and reads the signing secret from the database, so using it already requires shell
 * access to the server — strictly more than an administrator password.
 */

if (PHP_SAPI !== 'cli') {
    header('HTTP/1.1 404 Not Found');
    exit;
}

require_once __DIR__ . '/lib/Log.php';
require_once __DIR__ . '/lib/Bootstrap.php';
require_once __DIR__ . '/lib/Db.php';
require_once __DIR__ . '/lib/Token.php';

$problem = UpdaterBootstrap::init();
if ($problem !== null) {
    fwrite(STDERR, $problem['title'] . "\n" . strip_tags($problem['message']) . "\n");
    if (!empty($problem['command'])) {
        fwrite(STDERR, "\n" . $problem['command'] . "\n");
    }
    exit(1);
}

$lifetime = 7200; // two hours, matching the banner's links
$expires = time() + $lifetime;
$signature = UpdaterToken::signature($expires);

if ($signature === null) {
    fwrite(STDERR,
        "Could not read this installation's signing secret from the database.\n"
        . "Check that the IceHRM database is reachable and that SystemData contains\n"
        . "'Instance: Signing Secret' (it is created the first time an administrator signs in).\n");
    exit(1);
}

$base = defined('CLIENT_BASE_URL') ? rtrim(CLIENT_BASE_URL, '/') : '';
if ($base !== '') {
    $root = substr($base, 0, strrpos($base, '/') + 1);
    $url = $root . 'updater/?e=' . $expires . '&t=' . $signature;
} else {
    $url = '/updater/?e=' . $expires . '&t=' . $signature;
}

echo "\nUpdater link (valid until " . date('Y-m-d H:i:s', $expires) . "):\n\n";
echo "  " . $url . "\n\n";
echo "Open it in a browser and sign in as an IceHRM administrator.\n";
